web:
  build: .
  command: 'bash -c ''npm start'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  env_file: .env
  links:
    - db
    - redis
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
  env_file: .env
  links:
    - db
    - redis
db:
  image: mongo
redis:
  image: redis
